on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  release-please:
    name: Release
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # In order to publish a release that triggers another workflow,
          # we use a custom Personal Access Token rather than default
          # secrets.GITHUB_TOKEN. 
          token: ${{ secrets.HUMI_CI_TOKEN }}
